spring:

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: meteor4
    password: 12345
    url: jdbc:mariadb://localhost:3306/springboot?characterEncoding=UTF-8

  jpa:
    open-in-view: true
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      use-new-id-generator-mappings: false
      ddl-auto: none
    show_sql: true
    generate-ddl: false
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true